# Generated by Django 5.1.2 on 2024-11-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepeda',
            fields=[
                ('id_sepeda', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_sepeda', models.CharField(choices=[('SG', 'Sepeda Gunung'), ('SE', 'Sepeda Elektrik'), ('SA', 'Sepeda Anak'), ('S', 'Skuter')], max_length=50)),
                ('kondisi_sepeda', models.CharField(choices=[('R', 'Rusak'), ('B', 'Baik')], max_length=50)),
                ('status_sepeda', models.CharField(choices=[('T', 'Tersedia'), ('TT', 'Tidak Tersedia'), ('D', 'Dipinjam')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stasiun',
            fields=[
                ('id_stasiun', models.AutoField(primary_key=True, serialize=False)),
                ('nama_stasiun', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=200)),
                ('kapasitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('username', models.CharField(default='default_username', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_telp', models.CharField(max_length=15, unique=True)),
                ('alamat', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjaman', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_pengambilan', models.DateTimeField(auto_now_add=True)),
                ('waktu_pengembalian', models.DateTimeField(blank=True, null=True)),
                ('total_biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_pembayaran', models.CharField(default='Belum Dibayar', max_length=20)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_set', to='gowesin.pelanggan')),
                ('sepeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_set', to='gowesin.sepeda')),
                ('stasiun_pengambilan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengambilan_set', to='gowesin.stasiun')),
                ('stasiun_pengembalian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengembalian_set', to='gowesin.stasiun')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('waktu_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peminjaman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='gowesin.peminjaman')),
            ],
        ),
        migrations.AddField(
            model_name='sepeda',
            name='stasiun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepeda_set', to='gowesin.stasiun'),
        ),
    ]
