# Generated by Django 5.1.2 on 2024-11-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gowesin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='alamat',
        ),
    ]
