# Generated by Django 5.1.2 on 2024-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowesin', '0002_remove_pelanggan_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stasiun',
            name='jumlah_sepeda',
            field=models.IntegerField(default=0),
        ),
    ]
