# Generated by Django 5.1.2 on 2024-11-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gowesin', '0003_stasiun_jumlah_sepeda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stasiun',
            name='jumlah_sepeda',
        ),
    ]
